### PR TITLE
Create XDOCKER-8: Also offer an alpine-based image to reduce download…

### PR DESCRIPTION
**Pull request by Durgesh4993**
XDOCKER-8: Also offer an alpine-based image to reduce download size in swift

### CODE REVIEW

**Comment by Durgesh4993** [comment]
Hello sir , i want to contribute how i start contribution please help me

**Comment by tmortagne** [comment]
@Durgesh4993 if it's for the GSOC you might want to look at https://dev.xwiki.org/xwiki/bin/view/GoogleSummerOfCode/, otherwise you have the more general https://dev.xwiki.org/xwiki/bin/view/Community/Contributing

**Comment by GitHubGov** [comment]
My account was hacked. I've never done. I will change my password.

**Comment by Durgesh4993** [comment]
ok sir

**Pull request closed without merging**
